name: Sync to Hugging Face Space

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sync-space:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: mozilla-ai/surf-spot-finder
      HTTPS_REPO: https://${{ secrets.HF_USERNAME }}:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/mozilla-ai/surf-spot-finder
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # use a dynamic branch name that way we can deploy feature branches to the HF space if we want
      - name: Set branch name env var
        run: |
          echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

      - run: git clone ${{ env.HTTPS_REPO}} hf-space

      - run: |
          cp demo/**/* hf-space

      - run: |
          cd hf-space
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Sync with https://github.com/${{ env.REPO_NAME }}"

      - name: Push to Hugging Face
        run: |
          cd hf-space
          git push ${{ env.HTTPS_REPO}} ${{ env.BRANCH_NAME }}:main
